### PR TITLE
import inbucket chart from helm/charts that is deprecated

### PR DESCRIPTION
**Pull request by cpanato**
Import the inbucket helm chart from the deprecated helm/charts repos and fix issue related to the clusterIP.
After the approval, I need to watch the post-merge workflow to check if the release will be created correctly.

and after that we can add/fix any issues with this helm chart :)

### CODE REVIEW

**Comment by cpanato** [comment]
ok, now we have a fun part! :) debugging why CI is not working as I expected

**Comment by cpanato** [comment]
the inbucket helm chart was installed correctly and was accessible

**Review by jhillyerd — APPROVED** [review]

**Comment by jhillyerd** [comment]
Looks good to me, I'll let you merge when ready

**Comment by cpanato** [comment]
if any failures happen due to the release, I will try to fix it

**Comment by cpanato** [comment]
yay! 1.0.0 released :)

**Comment by jhillyerd** [comment]
Big thank you, I wouldn't know where to begin on this.

**Pull request merged**
