### PR TITLE
Allow service port name override

### PR DESCRIPTION
**Pull request by rubel-ahammad**
Fixes: https://github.com/inbucket/inbucket-community/issues/40

### CODE REVIEW

**Review by cpanato — CHANGES_REQUESTED** [review]
can you please bump the chart version

**Comment by rubel-ahammad** [comment]
> can you please bump the chart version

I added an option in the chart. So I believe it is a feature change and the new version should be 2.4.0. @cpanato what do you think?

**Comment by cpanato** [comment]
> > can you please bump the chart version
> 
> I added an option in the chart. So I believe it is a feature change and the new version should be 2.4.0. @cpanato what do you think?

That is fine, the feature is not changing the actual behavior so we can consider a patch, but this is also fine

Thanks for doing this!

**Comment by cpanato** [comment]
```
Error: UPGRADE FAILED: template: inbucket/templates/service.yaml:29:22: executing "inbucket/templates/service.yaml" at <.Values.service.portName.http>: nil pointer evaluating interface {}.http
```

**Comment by rubel-ahammad** [comment]
Hi, I have pushed the fix. Could you please review again?

**Review by cpanato — APPROVED** [review]
thanks

**Pull request merged**
