### PR TITLE
fix: Fix web greeting file path

### PR DESCRIPTION
**Pull request by josedev-union**

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
thanks

**Comment by jhillyerd** [comment]
This is not correct.  Greeting is the the "message of the day" content, which Inbucket embeds within the front page, it's meant to be customized by the user.  `ui/index.html` is essentially the loader for the entire "single page webapp" that is Inbucket's UI.

**Comment by josedev-union** [comment]
> This is not correct. Greeting is the the "message of the day" content, which Inbucket embeds within the front page, it's meant to be customized by the user. `ui/index.html` is essentially the loader for the entire "single page webapp" that is Inbucket's UI.

@jhillyerd thanks for clarifying. But inbucket web console is not working  with the default configuration because of unexisting `greeting.html` file.
I think if that greeting file is optional, the server should work. Or if that is mandatory, the container image should include a default file so the helm chart works out of the box?

**Comment by jhillyerd** [comment]
I've created #20 as a place to discuss

**Comment by corey-aloia** [comment]
I just noticed this PR.... I opened a similar one yesterday: https://github.com/inbucket/inbucket-community/pull/23

I believe the PR I open is correct, as `/config` is what is used when running the container. I also have tested this locally. See: https://github.com/inbucket/inbucket/blob/1b5a783dbd26677b3d73d38c7e7113dc12d4194a/etc/docker/defaults/start-inbucket.sh#L7

**Comment by jhillyerd** [comment]
obsoleted by #23

**Pull request closed without merging**
